export const RECOMMEND_ARTIST = "RECOMMEND_ARTIST";
export const RECOMMEND_TRACK = "RECOMMEND_TRACK";

export const GET_TRACK = "GET_TRACK";
export const GET_ARTIST = "GET_ARTIST";
export const GET_TAG = "GET_TAG";

export const SET_TAG_NAME = "SET_TAG_NAME";
export const SET_GEO_NAME = "SET_GEO_NAME";

export const GET_TOP_ALBUMS = "GET_TOP_ALBUMS";
export const GET_TOP_TRACKS = "GET_TOP_TRACKS";
export const GET_TOP_ALBUM_TAGS = "GET_TOP_ALBUM_TAGS";
export const GET_TOP_ARTIST_TAGS = "GET_TOP_ARTIST_TAGS";
export const GET_TOP_TRACK_TAGS = "GET_TOP_TRACK_TAGS";
export const GET_TOP_TAGS = "GET_TOP_TAGS";

export const GET_SIMILAR_TRACK = "GET_SIMILAR_TRACK";

export const RESET_TRACK_STATE = "RESET_TRACK_STATE";
export const RESET_ARTIST_STATE = "RESET_ARTIST_STATE";
export const RESET_TAG_STATE = "RESET_TAG_STATE";
export const RESET_GEO_STATE = "RESET_GEO_STATE";

export const GET_GEO_TOP_ARTISTS = "GET_GEO_TOP_ARTISTS";
export const GET_GEO_TOP_TRACKS = "GET_GEO_TOP_TRACKS";

export const TOGGLE_LOADING = "TOGGLE_LOADING";

export const CHART_GET_TOP_TRACKS = "CHART_GET_TOP_TRACKS";
export const CHART_GET_TOP_ARTISTS = "CHART_GET_TOP_ARTISTS";
export const CHART_GET_TOP_TAGS = "CHART_GET_TOP_TAGS";
export const CHART_RESET = "CHART_RESET";
